#!/bin/bash
echo $PATH | tr -s : n | wc -l
echo /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | tr -s ':' '\n' | wc -l
echo /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | tr -s ':' '\n' | wc -l
echo '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' | tr -s ':' '\n' | wc -l
echo $PATH | tr -s ":" "n" | wc -l
echo $PATH | tr -s ":" "\n" | wc -l
echo $PATH | tr -s : n | wc -l
echo /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | tr -s ':' '\n' | wc -l
