#!/usr/bin/env bash
# Install and configure HAproxy on  lb-01 server
sudo apt-get update
sudo apt-get -y install haproxy
config="frontend http
\tbind *:80
\tmode http
\tdefault_backend web-backend
backend web-backend
\tbalance roundrobin
\tserver 22190-web-01 44.192.74.104 check
\tserver 22190-web-02 35.173.42.16 check"
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
