#!/usr/bin/env bash
# This script gives you information about the school file

FILE=school

# if the file exists
if [ -a $FILE ]
then
	echo "school file exists"

	# if the file is empty/non-empty
	if [ -s $FILE ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# if the file is a regular file
	if [ -f $FILE ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
